# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b602c31b708e2e49f780edd19e331dccff2ec8bd5baa1357fdc629a449b62d1201a1a68a6063a1008018534d5fea0ead66bbb661cc4eb74e98dcbabf3f1d9c

test:
  secret_key_base: b0745cfde2ece8f0febf7da0dc6d51b998e2a60be65c7bd80957b83996c03fc7d1051e74950d11f90b502afa24c0fe6eb1c01788eb9989fa7c5171ff00e19aaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
